#!/usr/bin/env node

// ============================================================================
// Follow Builders — Prepare Digest (Local Mode)
// ============================================================================
// Reads feeds and prompts from local files instead of GitHub raw URLs.
// Run generate-feed.js first to produce the feed JSON files.
//
// Usage: node prepare-digest.js
// Output: JSON to stdout
// ============================================================================

import { readFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

// -- Constants ---------------------------------------------------------------

const USER_DIR = join(homedir(), '.follow-builders');
const CONFIG_PATH = join(USER_DIR, 'config.json');

const scriptDir = decodeURIComponent(new URL('.', import.meta.url).pathname);
const SKILL_DIR = join(scriptDir, '..');

const FEED_X_PATH = join(SKILL_DIR, 'feed-x.json');
const FEED_PODCASTS_PATH = join(SKILL_DIR, 'feed-podcasts.json');
const FEED_BLOGS_PATH = join(SKILL_DIR, 'feed-blogs.json');

const PROMPT_FILES = [
  'summarize-podcast.md',
  'summarize-tweets.md',
  'summarize-blogs.md',
  'digest-intro.md',
  'translate.md'
];

// -- Helpers -----------------------------------------------------------------

async function readJSON(path) {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(await readFile(path, 'utf-8'));
  } catch {
    return null;
  }
}

// -- Main --------------------------------------------------------------------

async function main() {
  const errors = [];

  // 1. Read user config
  let config = {
    language: 'en',
    frequency: 'daily',
    delivery: { method: 'stdout' }
  };
  if (existsSync(CONFIG_PATH)) {
    try {
      config = JSON.parse(await readFile(CONFIG_PATH, 'utf-8'));
    } catch (err) {
      errors.push(`Could not read config: ${err.message}`);
    }
  }

  // 2. Read local feeds (generated by generate-feed.js)
  const [feedX, feedPodcasts, feedBlogs] = await Promise.all([
    readJSON(FEED_X_PATH),
    readJSON(FEED_PODCASTS_PATH),
    readJSON(FEED_BLOGS_PATH)
  ]);

  if (!feedX) errors.push('feed-x.json not found — run generate-feed.js first');
  if (!feedPodcasts) errors.push('feed-podcasts.json not found — run generate-feed.js first');
  if (!feedBlogs) errors.push('feed-blogs.json not found — run generate-feed.js first');

  // 3. Load prompts: user custom (~/.follow-builders/prompts/) > skill defaults
  const prompts = {};
  const localPromptsDir = join(SKILL_DIR, 'prompts');
  const userPromptsDir = join(USER_DIR, 'prompts');

  for (const filename of PROMPT_FILES) {
    const key = filename.replace('.md', '').replace(/-/g, '_');
    const userPath = join(userPromptsDir, filename);
    const localPath = join(localPromptsDir, filename);

    if (existsSync(userPath)) {
      prompts[key] = await readFile(userPath, 'utf-8');
    } else if (existsSync(localPath)) {
      prompts[key] = await readFile(localPath, 'utf-8');
    } else {
      errors.push(`Could not load prompt: ${filename}`);
    }
  }

  // 4. Build output — everything the LLM needs in one blob
  const output = {
    status: 'ok',
    generatedAt: new Date().toISOString(),

    config: {
      language: config.language || 'en',
      frequency: config.frequency || 'daily',
      delivery: config.delivery || { method: 'stdout' }
    },

    podcasts: feedPodcasts?.podcasts || [],
    x: feedX?.x || [],
    blogs: feedBlogs?.blogs || [],

    stats: {
      podcastEpisodes: feedPodcasts?.podcasts?.length || 0,
      xBuilders: feedX?.x?.length || 0,
      totalTweets: (feedX?.x || []).reduce((sum, a) => sum + a.tweets.length, 0),
      blogPosts: feedBlogs?.blogs?.length || 0,
      feedGeneratedAt: feedX?.generatedAt || feedPodcasts?.generatedAt || feedBlogs?.generatedAt || null
    },

    prompts,
    errors: errors.length > 0 ? errors : undefined
  };

  console.log(JSON.stringify(output, null, 2));
}

main().catch(err => {
  console.error(JSON.stringify({
    status: 'error',
    message: err.message
  }));
  process.exit(1);
});
